server:
  port: 8765
  mock-server-port: 1001
  servlet:
    context-path: /order-service
    max-http-header-size: 61440
    tomcat:
      max-http-post-size: 5MB

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/order_db?serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/db/db-changelog-master.yaml
  zipkin:
    enabled: true

ribbon:
  connectTimeout: 10000
  readTimeout: 10000
logging:
  file: ./logs/order-server.log
  level:
    org:
      springframework:
        cloud: debug
        web: debug
        security: debug
    com:
      dangtuan: debug

app:
  public-key: public_key.txt
  allowed-endpoints:
    - /oauth/**
    - /actuator/**
    - /v2/api-docs, /swagger-resources/**, /swagger-ui.html**, /webjars/**, favicon.ico

kafka:
  bootstrapAddress: localhost:9092
  order:
    topic:
      name: order
      group: ORDER_SERVICE
  delivery:
    topic:
      name: delivery
      group: DELIVERY_SERVICE

#sentry:
#  dsn: {your_url}
#  exception-resolver-order: 2147483647

management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
  endpoints:
    web:
      exposure:
        include: refresh, prometheus, info, health
api:
  payment: http://localhost:8087/v1/payment
  enable: true