server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  file: ./logs/order-server.log
  level:
    org:
      springframework:
        cloud: debug
        web: debug
        security: debug
    com:
      dangtuan: debug

sentry:
  dsn: {your_url}
  exception-resolver-order: 2147483647